apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: k8s-defense
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "infinity"]
    securityContext:
      allowPrivilegeEscalation: true    # 特権昇格許可
